name: Deploy

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

# Add concurrency group to prevent multiple deployments at once
concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    # Only proceed if the CI workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Add deployment steps here based on your preferred platform
      # Option 1: Vercel deployment
      - name: Deploy to Vercel
        run: |
          # Install Vercel CLI
          npm install -g vercel@latest
          
          # Pull Vercel project info
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          
          # Build the project
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          
          # Deploy to Vercel
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Option 2: Netlify deployment (alternative)
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2
      #   with:
      #     publish-dir: './dist'
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #     enable-pull-request-comment: false
      #     enable-commit-comment: false
      #     overwrites-pull-request-comment: true
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: env.GITHUB_PAGES_TOKEN != null
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true